// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: ChallengeService/challenge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParticipantMetadata struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	JoinTimeUnix      int64                                `protobuf:"varint,1,opt,name=joinTimeUnix,proto3" json:"joinTimeUnix,omitempty"`
	ProblemsDone      map[string]*ChallengeProblemMetadata `protobuf:"bytes,2,rep,name=problemsDone,proto3" json:"problemsDone,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProblemsAttempted int32                                `protobuf:"varint,3,opt,name=problemsAttempted,proto3" json:"problemsAttempted,omitempty"`
	TotalScore        int32                                `protobuf:"varint,4,opt,name=totalScore,proto3" json:"totalScore,omitempty"`
	LastConnectedUnix int64                                `protobuf:"varint,5,opt,name=lastConnectedUnix,proto3" json:"lastConnectedUnix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParticipantMetadata) Reset() {
	*x = ParticipantMetadata{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantMetadata) ProtoMessage() {}

func (x *ParticipantMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantMetadata.ProtoReflect.Descriptor instead.
func (*ParticipantMetadata) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *ParticipantMetadata) GetJoinTimeUnix() int64 {
	if x != nil {
		return x.JoinTimeUnix
	}
	return 0
}

func (x *ParticipantMetadata) GetProblemsDone() map[string]*ChallengeProblemMetadata {
	if x != nil {
		return x.ProblemsDone
	}
	return nil
}

func (x *ParticipantMetadata) GetProblemsAttempted() int32 {
	if x != nil {
		return x.ProblemsAttempted
	}
	return 0
}

func (x *ParticipantMetadata) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ParticipantMetadata) GetLastConnectedUnix() int64 {
	if x != nil {
		return x.LastConnectedUnix
	}
	return 0
}

type ChallengeProblemMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProblemId       string                 `protobuf:"bytes,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Score           int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	TimeTaken       int64                  `protobuf:"varint,3,opt,name=timeTaken,proto3" json:"timeTaken,omitempty"`
	CompletedAtUnix int64                  `protobuf:"varint,4,opt,name=completedAtUnix,proto3" json:"completedAtUnix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChallengeProblemMetadata) Reset() {
	*x = ChallengeProblemMetadata{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeProblemMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeProblemMetadata) ProtoMessage() {}

func (x *ChallengeProblemMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeProblemMetadata.ProtoReflect.Descriptor instead.
func (*ChallengeProblemMetadata) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeProblemMetadata) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *ChallengeProblemMetadata) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ChallengeProblemMetadata) GetTimeTaken() int64 {
	if x != nil {
		return x.TimeTaken
	}
	return 0
}

func (x *ChallengeProblemMetadata) GetCompletedAtUnix() int64 {
	if x != nil {
		return x.CompletedAtUnix
	}
	return 0
}

type SubmissionMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId    string                 `protobuf:"bytes,1,opt,name=submissionId,proto3" json:"submissionId,omitempty"`
	TimeTakenMillis int64                  `protobuf:"varint,2,opt,name=timeTakenMillis,proto3" json:"timeTakenMillis,omitempty"`
	Points          int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	UserCode        string                 `protobuf:"bytes,4,opt,name=userCode,proto3" json:"userCode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmissionMetadata) Reset() {
	*x = SubmissionMetadata{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionMetadata) ProtoMessage() {}

func (x *SubmissionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionMetadata.ProtoReflect.Descriptor instead.
func (*SubmissionMetadata) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{2}
}

func (x *SubmissionMetadata) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmissionMetadata) GetTimeTakenMillis() int64 {
	if x != nil {
		return x.TimeTakenMillis
	}
	return 0
}

func (x *SubmissionMetadata) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *SubmissionMetadata) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

type SubmissionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     string                 `protobuf:"bytes,1,opt,name=problemId,proto3" json:"problemId,omitempty"`
	Submission    *SubmissionMetadata    `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionEntry) Reset() {
	*x = SubmissionEntry{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionEntry) ProtoMessage() {}

func (x *SubmissionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionEntry.ProtoReflect.Descriptor instead.
func (*SubmissionEntry) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{3}
}

func (x *SubmissionEntry) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *SubmissionEntry) GetSubmission() *SubmissionMetadata {
	if x != nil {
		return x.Submission
	}
	return nil
}

type UserSubmissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Entries       []*SubmissionEntry     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSubmissions) Reset() {
	*x = UserSubmissions{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubmissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubmissions) ProtoMessage() {}

func (x *UserSubmissions) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubmissions.ProtoReflect.Descriptor instead.
func (*UserSubmissions) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{4}
}

func (x *UserSubmissions) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSubmissions) GetEntries() []*SubmissionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LeaderboardEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProblemsCompleted int32                  `protobuf:"varint,2,opt,name=problemsCompleted,proto3" json:"problemsCompleted,omitempty"`
	TotalScore        int32                  `protobuf:"varint,3,opt,name=totalScore,proto3" json:"totalScore,omitempty"`
	Rank              int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetProblemsCompleted() int32 {
	if x != nil {
		return x.ProblemsCompleted
	}
	return 0
}

func (x *LeaderboardEntry) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type QuestionPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionIds   []string               `protobuf:"bytes,1,rep,name=questionIds,proto3" json:"questionIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionPool) Reset() {
	*x = QuestionPool{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionPool) ProtoMessage() {}

func (x *QuestionPool) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionPool.ProtoReflect.Descriptor instead.
func (*QuestionPool) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionPool) GetQuestionIds() []string {
	if x != nil {
		return x.QuestionIds
	}
	return nil
}

type ChallengeConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxUsers           int32                  `protobuf:"varint,1,opt,name=maxUsers,proto3" json:"maxUsers,omitempty"`
	MaxEasyQuestions   int32                  `protobuf:"varint,2,opt,name=maxEasyQuestions,proto3" json:"maxEasyQuestions,omitempty"`
	MaxMediumQuestions int32                  `protobuf:"varint,3,opt,name=maxMediumQuestions,proto3" json:"maxMediumQuestions,omitempty"`
	MaxHardQuestions   int32                  `protobuf:"varint,4,opt,name=maxHardQuestions,proto3" json:"maxHardQuestions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChallengeConfig) Reset() {
	*x = ChallengeConfig{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeConfig) ProtoMessage() {}

func (x *ChallengeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeConfig.ProtoReflect.Descriptor instead.
func (*ChallengeConfig) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{7}
}

func (x *ChallengeConfig) GetMaxUsers() int32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

func (x *ChallengeConfig) GetMaxEasyQuestions() int32 {
	if x != nil {
		return x.MaxEasyQuestions
	}
	return 0
}

func (x *ChallengeConfig) GetMaxMediumQuestions() int32 {
	if x != nil {
		return x.MaxMediumQuestions
	}
	return 0
}

func (x *ChallengeConfig) GetMaxHardQuestions() int32 {
	if x != nil {
		return x.MaxHardQuestions
	}
	return 0
}

type ChallengeRecord struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	ChallengeId         string                          `protobuf:"bytes,1,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	CreatorId           string                          `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Title               string                          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsPrivate           bool                            `protobuf:"varint,4,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	Password            string                          `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Status              string                          `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TimeLimitMillis     int64                           `protobuf:"varint,7,opt,name=timeLimitMillis,proto3" json:"timeLimitMillis,omitempty"`
	StartTimeUnix       int64                           `protobuf:"varint,8,opt,name=startTimeUnix,proto3" json:"startTimeUnix,omitempty"`
	Participants        map[string]*ParticipantMetadata `protobuf:"bytes,9,rep,name=participants,proto3" json:"participants,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Submissions         []*UserSubmissions              `protobuf:"bytes,10,rep,name=submissions,proto3" json:"submissions,omitempty"`
	Leaderboard         []*LeaderboardEntry             `protobuf:"bytes,11,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	Config              *ChallengeConfig                `protobuf:"bytes,12,opt,name=config,proto3" json:"config,omitempty"`
	ProcessedProblemIds []string                        `protobuf:"bytes,13,rep,name=processedProblemIds,proto3" json:"processedProblemIds,omitempty"` //user can pass predefined qns in this, if len() > 1, ignore auto gen via ratio.
	CreatedAt           int64                           `protobuf:"varint,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ProblemCount        int64                           `protobuf:"varint,15,opt,name=problemCount,proto3" json:"problemCount,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChallengeRecord) Reset() {
	*x = ChallengeRecord{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRecord) ProtoMessage() {}

func (x *ChallengeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRecord.ProtoReflect.Descriptor instead.
func (*ChallengeRecord) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{8}
}

func (x *ChallengeRecord) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeRecord) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *ChallengeRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChallengeRecord) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *ChallengeRecord) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ChallengeRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChallengeRecord) GetTimeLimitMillis() int64 {
	if x != nil {
		return x.TimeLimitMillis
	}
	return 0
}

func (x *ChallengeRecord) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *ChallengeRecord) GetParticipants() map[string]*ParticipantMetadata {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ChallengeRecord) GetSubmissions() []*UserSubmissions {
	if x != nil {
		return x.Submissions
	}
	return nil
}

func (x *ChallengeRecord) GetLeaderboard() []*LeaderboardEntry {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *ChallengeRecord) GetConfig() *ChallengeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChallengeRecord) GetProcessedProblemIds() []string {
	if x != nil {
		return x.ProcessedProblemIds
	}
	return nil
}

func (x *ChallengeRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChallengeRecord) GetProblemCount() int64 {
	if x != nil {
		return x.ProblemCount
	}
	return 0
}

type GetChallengeRoomInfoMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRoomInfoMetadataRequest) Reset() {
	*x = GetChallengeRoomInfoMetadataRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRoomInfoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRoomInfoMetadataRequest) ProtoMessage() {}

func (x *GetChallengeRoomInfoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRoomInfoMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRoomInfoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{9}
}

func (x *GetChallengeRoomInfoMetadataRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *GetChallengeRoomInfoMetadataRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type GetChallengeRoomInfoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *ChallengeRecord       `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRoomInfoMetadataResponse) Reset() {
	*x = GetChallengeRoomInfoMetadataResponse{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRoomInfoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRoomInfoMetadataResponse) ProtoMessage() {}

func (x *GetChallengeRoomInfoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRoomInfoMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeRoomInfoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{10}
}

func (x *GetChallengeRoomInfoMetadataResponse) GetChallenge() *ChallengeRecord {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{11}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ChallengeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenges    []*ChallengeRecord     `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeListResponse) Reset() {
	*x = ChallengeListResponse{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeListResponse) ProtoMessage() {}

func (x *ChallengeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeListResponse.ProtoReflect.Descriptor instead.
func (*ChallengeListResponse) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{12}
}

func (x *ChallengeListResponse) GetChallenges() []*ChallengeRecord {
	if x != nil {
		return x.Challenges
	}
	return nil
}

func (x *ChallengeListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetChallengeHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,3,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeHistoryRequest) Reset() {
	*x = GetChallengeHistoryRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeHistoryRequest) ProtoMessage() {}

func (x *GetChallengeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{13}
}

func (x *GetChallengeHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChallengeHistoryRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetChallengeHistoryRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type GetOwnersActiveChallengesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnersActiveChallengesRequest) Reset() {
	*x = GetOwnersActiveChallengesRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnersActiveChallengesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnersActiveChallengesRequest) ProtoMessage() {}

func (x *GetOwnersActiveChallengesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnersActiveChallengesRequest.ProtoReflect.Descriptor instead.
func (*GetOwnersActiveChallengesRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{14}
}

func (x *GetOwnersActiveChallengesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOwnersActiveChallengesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PushSubmissionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=userCode,proto3" json:"userCode,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ProblemId     string                 `protobuf:"bytes,4,opt,name=problemId,proto3" json:"problemId,omitempty"`
	SubmissionId  string                 `protobuf:"bytes,6,opt,name=submissionId,proto3" json:"submissionId,omitempty"`
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	IsSuccessful  bool                   `protobuf:"varint,8,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
	TraceId       string                 `protobuf:"bytes,9,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSubmissionStatusRequest) Reset() {
	*x = PushSubmissionStatusRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSubmissionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSubmissionStatusRequest) ProtoMessage() {}

func (x *PushSubmissionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSubmissionStatusRequest.ProtoReflect.Descriptor instead.
func (*PushSubmissionStatusRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{15}
}

func (x *PushSubmissionStatusRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *PushSubmissionStatusRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *PushSubmissionStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushSubmissionStatusRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *PushSubmissionStatusRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *PushSubmissionStatusRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PushSubmissionStatusRequest) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *PushSubmissionStatusRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PushSubmissionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSubmissionStatusResponse) Reset() {
	*x = PushSubmissionStatusResponse{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSubmissionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSubmissionStatusResponse) ProtoMessage() {}

func (x *PushSubmissionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSubmissionStatusResponse.ProtoReflect.Descriptor instead.
func (*PushSubmissionStatusResponse) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{16}
}

func (x *PushSubmissionStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushSubmissionStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AbandonChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	CreatorId     string                 `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonChallengeRequest) Reset() {
	*x = AbandonChallengeRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonChallengeRequest) ProtoMessage() {}

func (x *AbandonChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonChallengeRequest.ProtoReflect.Descriptor instead.
func (*AbandonChallengeRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{17}
}

func (x *AbandonChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *AbandonChallengeRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type AbandonChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorType     string                 `protobuf:"bytes,3,opt,name=errorType,proto3" json:"errorType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonChallengeResponse) Reset() {
	*x = AbandonChallengeResponse{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonChallengeResponse) ProtoMessage() {}

func (x *AbandonChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonChallengeResponse.ProtoReflect.Descriptor instead.
func (*AbandonChallengeResponse) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{18}
}

func (x *AbandonChallengeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbandonChallengeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AbandonChallengeResponse) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

type GetFullChallengeDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullChallengeDataRequest) Reset() {
	*x = GetFullChallengeDataRequest{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullChallengeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullChallengeDataRequest) ProtoMessage() {}

func (x *GetFullChallengeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullChallengeDataRequest.ProtoReflect.Descriptor instead.
func (*GetFullChallengeDataRequest) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{19}
}

func (x *GetFullChallengeDataRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *GetFullChallengeDataRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type GetFullChallengeDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *ChallengeRecord       `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullChallengeDataResponse) Reset() {
	*x = GetFullChallengeDataResponse{}
	mi := &file_ChallengeService_challenge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullChallengeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullChallengeDataResponse) ProtoMessage() {}

func (x *GetFullChallengeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ChallengeService_challenge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullChallengeDataResponse.ProtoReflect.Descriptor instead.
func (*GetFullChallengeDataResponse) Descriptor() ([]byte, []int) {
	return file_ChallengeService_challenge_proto_rawDescGZIP(), []int{20}
}

func (x *GetFullChallengeDataResponse) GetChallenge() *ChallengeRecord {
	if x != nil {
		return x.Challenge
	}
	return nil
}

var File_ChallengeService_challenge_proto protoreflect.FileDescriptor

const file_ChallengeService_challenge_proto_rawDesc = "" +
	"\n" +
	" ChallengeService/challenge.proto\x12\tchallenge\"\xf1\x02\n" +
	"\x13ParticipantMetadata\x12\"\n" +
	"\fjoinTimeUnix\x18\x01 \x01(\x03R\fjoinTimeUnix\x12T\n" +
	"\fproblemsDone\x18\x02 \x03(\v20.challenge.ParticipantMetadata.ProblemsDoneEntryR\fproblemsDone\x12,\n" +
	"\x11problemsAttempted\x18\x03 \x01(\x05R\x11problemsAttempted\x12\x1e\n" +
	"\n" +
	"totalScore\x18\x04 \x01(\x05R\n" +
	"totalScore\x12,\n" +
	"\x11lastConnectedUnix\x18\x05 \x01(\x03R\x11lastConnectedUnix\x1ad\n" +
	"\x11ProblemsDoneEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.challenge.ChallengeProblemMetadataR\x05value:\x028\x01\"\x96\x01\n" +
	"\x18ChallengeProblemMetadata\x12\x1c\n" +
	"\tproblemId\x18\x01 \x01(\tR\tproblemId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1c\n" +
	"\ttimeTaken\x18\x03 \x01(\x03R\ttimeTaken\x12(\n" +
	"\x0fcompletedAtUnix\x18\x04 \x01(\x03R\x0fcompletedAtUnix\"\x96\x01\n" +
	"\x12SubmissionMetadata\x12\"\n" +
	"\fsubmissionId\x18\x01 \x01(\tR\fsubmissionId\x12(\n" +
	"\x0ftimeTakenMillis\x18\x02 \x01(\x03R\x0ftimeTakenMillis\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\x12\x1a\n" +
	"\buserCode\x18\x04 \x01(\tR\buserCode\"n\n" +
	"\x0fSubmissionEntry\x12\x1c\n" +
	"\tproblemId\x18\x01 \x01(\tR\tproblemId\x12=\n" +
	"\n" +
	"submission\x18\x02 \x01(\v2\x1d.challenge.SubmissionMetadataR\n" +
	"submission\"_\n" +
	"\x0fUserSubmissions\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.challenge.SubmissionEntryR\aentries\"\x8c\x01\n" +
	"\x10LeaderboardEntry\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x11problemsCompleted\x18\x02 \x01(\x05R\x11problemsCompleted\x12\x1e\n" +
	"\n" +
	"totalScore\x18\x03 \x01(\x05R\n" +
	"totalScore\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"0\n" +
	"\fQuestionPool\x12 \n" +
	"\vquestionIds\x18\x01 \x03(\tR\vquestionIds\"\xb5\x01\n" +
	"\x0fChallengeConfig\x12\x1a\n" +
	"\bmaxUsers\x18\x01 \x01(\x05R\bmaxUsers\x12*\n" +
	"\x10maxEasyQuestions\x18\x02 \x01(\x05R\x10maxEasyQuestions\x12.\n" +
	"\x12maxMediumQuestions\x18\x03 \x01(\x05R\x12maxMediumQuestions\x12*\n" +
	"\x10maxHardQuestions\x18\x04 \x01(\x05R\x10maxHardQuestions\"\xe1\x05\n" +
	"\x0fChallengeRecord\x12 \n" +
	"\vchallengeId\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tcreatorId\x18\x02 \x01(\tR\tcreatorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tisPrivate\x18\x04 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\x0ftimeLimitMillis\x18\a \x01(\x03R\x0ftimeLimitMillis\x12$\n" +
	"\rstartTimeUnix\x18\b \x01(\x03R\rstartTimeUnix\x12P\n" +
	"\fparticipants\x18\t \x03(\v2,.challenge.ChallengeRecord.ParticipantsEntryR\fparticipants\x12<\n" +
	"\vsubmissions\x18\n" +
	" \x03(\v2\x1a.challenge.UserSubmissionsR\vsubmissions\x12=\n" +
	"\vleaderboard\x18\v \x03(\v2\x1b.challenge.LeaderboardEntryR\vleaderboard\x122\n" +
	"\x06config\x18\f \x01(\v2\x1a.challenge.ChallengeConfigR\x06config\x120\n" +
	"\x13processedProblemIds\x18\r \x03(\tR\x13processedProblemIds\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\x03R\tcreatedAt\x12\"\n" +
	"\fproblemCount\x18\x0f \x01(\x03R\fproblemCount\x1a_\n" +
	"\x11ParticipantsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.challenge.ParticipantMetadataR\x05value:\x028\x01\"u\n" +
	"#GetChallengeRoomInfoMetadataRequest\x12 \n" +
	"\vchallengeId\x18\x01 \x01(\tR\vchallengeId\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"`\n" +
	"$GetChallengeRoomInfoMetadataResponse\x128\n" +
	"\tchallenge\x18\x01 \x01(\v2\x1a.challenge.ChallengeRecordR\tchallenge\"C\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"s\n" +
	"\x15ChallengeListResponse\x12:\n" +
	"\n" +
	"challenges\x18\x01 \x03(\v2\x1a.challenge.ChallengeRecordR\n" +
	"challenges\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x90\x01\n" +
	"\x1aGetChallengeHistoryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.challenge.PaginationRequestR\n" +
	"pagination\x12\x1c\n" +
	"\tisPrivate\x18\x03 \x01(\bR\tisPrivate\"x\n" +
	" GetOwnersActiveChallengesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.challenge.PaginationRequestR\n" +
	"pagination\"\x89\x02\n" +
	"\x1bPushSubmissionStatusRequest\x12\x1a\n" +
	"\buserCode\x18\x01 \x01(\tR\buserCode\x12 \n" +
	"\vchallengeId\x18\x02 \x01(\tR\vchallengeId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x1c\n" +
	"\tproblemId\x18\x04 \x01(\tR\tproblemId\x12\"\n" +
	"\fsubmissionId\x18\x06 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12\"\n" +
	"\fisSuccessful\x18\b \x01(\bR\fisSuccessful\x12\x18\n" +
	"\atraceId\x18\t \x01(\tR\atraceId\"R\n" +
	"\x1cPushSubmissionStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"Y\n" +
	"\x17AbandonChallengeRequest\x12 \n" +
	"\vchallengeId\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tcreatorId\x18\x02 \x01(\tR\tcreatorId\"l\n" +
	"\x18AbandonChallengeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\terrorType\x18\x03 \x01(\tR\terrorType\"m\n" +
	"\x1bGetFullChallengeDataRequest\x12 \n" +
	"\vchallengeId\x18\x01 \x01(\tR\vchallengeId\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01B\v\n" +
	"\t_password\"X\n" +
	"\x1cGetFullChallengeDataResponse\x128\n" +
	"\tchallenge\x18\x01 \x01(\v2\x1a.challenge.ChallengeRecordR\tchallenge2\xc0\x06\n" +
	"\x10ChallengeService\x12K\n" +
	"\x0fCreateChallenge\x12\x1a.challenge.ChallengeRecord\x1a\x1a.challenge.ChallengeRecord\"\x00\x12]\n" +
	"\x10AbandonChallenge\x12\".challenge.AbandonChallengeRequest\x1a#.challenge.AbandonChallengeResponse\"\x00\x12\x7f\n" +
	"\x1cGetChallengeRoomInfoMetadata\x12..challenge.GetChallengeRoomInfoMetadataRequest\x1a/.challenge.GetChallengeRoomInfoMetadataResponse\x12g\n" +
	"\x14GetFullChallengeData\x12&.challenge.GetFullChallengeDataRequest\x1a'.challenge.GetFullChallengeDataResponse\x12`\n" +
	"\x13GetChallengeHistory\x12%.challenge.GetChallengeHistoryRequest\x1a .challenge.ChallengeListResponse\"\x00\x12[\n" +
	"\x17GetActiveOpenChallenges\x12\x1c.challenge.PaginationRequest\x1a .challenge.ChallengeListResponse\"\x00\x12l\n" +
	"\x19GetOwnersActiveChallenges\x12+.challenge.GetOwnersActiveChallengesRequest\x1a .challenge.ChallengeListResponse\"\x00\x12i\n" +
	"\x14PushSubmissionStatus\x12&.challenge.PushSubmissionStatusRequest\x1a'.challenge.PushSubmissionStatusResponse\"\x00B=Z;github.com/lijuuu/ChallengeWssManagerService/internal/protob\x06proto3"

var (
	file_ChallengeService_challenge_proto_rawDescOnce sync.Once
	file_ChallengeService_challenge_proto_rawDescData []byte
)

func file_ChallengeService_challenge_proto_rawDescGZIP() []byte {
	file_ChallengeService_challenge_proto_rawDescOnce.Do(func() {
		file_ChallengeService_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ChallengeService_challenge_proto_rawDesc), len(file_ChallengeService_challenge_proto_rawDesc)))
	})
	return file_ChallengeService_challenge_proto_rawDescData
}

var file_ChallengeService_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ChallengeService_challenge_proto_goTypes = []any{
	(*ParticipantMetadata)(nil),                  // 0: challenge.ParticipantMetadata
	(*ChallengeProblemMetadata)(nil),             // 1: challenge.ChallengeProblemMetadata
	(*SubmissionMetadata)(nil),                   // 2: challenge.SubmissionMetadata
	(*SubmissionEntry)(nil),                      // 3: challenge.SubmissionEntry
	(*UserSubmissions)(nil),                      // 4: challenge.UserSubmissions
	(*LeaderboardEntry)(nil),                     // 5: challenge.LeaderboardEntry
	(*QuestionPool)(nil),                         // 6: challenge.QuestionPool
	(*ChallengeConfig)(nil),                      // 7: challenge.ChallengeConfig
	(*ChallengeRecord)(nil),                      // 8: challenge.ChallengeRecord
	(*GetChallengeRoomInfoMetadataRequest)(nil),  // 9: challenge.GetChallengeRoomInfoMetadataRequest
	(*GetChallengeRoomInfoMetadataResponse)(nil), // 10: challenge.GetChallengeRoomInfoMetadataResponse
	(*PaginationRequest)(nil),                    // 11: challenge.PaginationRequest
	(*ChallengeListResponse)(nil),                // 12: challenge.ChallengeListResponse
	(*GetChallengeHistoryRequest)(nil),           // 13: challenge.GetChallengeHistoryRequest
	(*GetOwnersActiveChallengesRequest)(nil),     // 14: challenge.GetOwnersActiveChallengesRequest
	(*PushSubmissionStatusRequest)(nil),          // 15: challenge.PushSubmissionStatusRequest
	(*PushSubmissionStatusResponse)(nil),         // 16: challenge.PushSubmissionStatusResponse
	(*AbandonChallengeRequest)(nil),              // 17: challenge.AbandonChallengeRequest
	(*AbandonChallengeResponse)(nil),             // 18: challenge.AbandonChallengeResponse
	(*GetFullChallengeDataRequest)(nil),          // 19: challenge.GetFullChallengeDataRequest
	(*GetFullChallengeDataResponse)(nil),         // 20: challenge.GetFullChallengeDataResponse
	nil,                                          // 21: challenge.ParticipantMetadata.ProblemsDoneEntry
	nil,                                          // 22: challenge.ChallengeRecord.ParticipantsEntry
}
var file_ChallengeService_challenge_proto_depIdxs = []int32{
	21, // 0: challenge.ParticipantMetadata.problemsDone:type_name -> challenge.ParticipantMetadata.ProblemsDoneEntry
	2,  // 1: challenge.SubmissionEntry.submission:type_name -> challenge.SubmissionMetadata
	3,  // 2: challenge.UserSubmissions.entries:type_name -> challenge.SubmissionEntry
	22, // 3: challenge.ChallengeRecord.participants:type_name -> challenge.ChallengeRecord.ParticipantsEntry
	4,  // 4: challenge.ChallengeRecord.submissions:type_name -> challenge.UserSubmissions
	5,  // 5: challenge.ChallengeRecord.leaderboard:type_name -> challenge.LeaderboardEntry
	7,  // 6: challenge.ChallengeRecord.config:type_name -> challenge.ChallengeConfig
	8,  // 7: challenge.GetChallengeRoomInfoMetadataResponse.challenge:type_name -> challenge.ChallengeRecord
	8,  // 8: challenge.ChallengeListResponse.challenges:type_name -> challenge.ChallengeRecord
	11, // 9: challenge.GetChallengeHistoryRequest.pagination:type_name -> challenge.PaginationRequest
	11, // 10: challenge.GetOwnersActiveChallengesRequest.pagination:type_name -> challenge.PaginationRequest
	8,  // 11: challenge.GetFullChallengeDataResponse.challenge:type_name -> challenge.ChallengeRecord
	1,  // 12: challenge.ParticipantMetadata.ProblemsDoneEntry.value:type_name -> challenge.ChallengeProblemMetadata
	0,  // 13: challenge.ChallengeRecord.ParticipantsEntry.value:type_name -> challenge.ParticipantMetadata
	8,  // 14: challenge.ChallengeService.CreateChallenge:input_type -> challenge.ChallengeRecord
	17, // 15: challenge.ChallengeService.AbandonChallenge:input_type -> challenge.AbandonChallengeRequest
	9,  // 16: challenge.ChallengeService.GetChallengeRoomInfoMetadata:input_type -> challenge.GetChallengeRoomInfoMetadataRequest
	19, // 17: challenge.ChallengeService.GetFullChallengeData:input_type -> challenge.GetFullChallengeDataRequest
	13, // 18: challenge.ChallengeService.GetChallengeHistory:input_type -> challenge.GetChallengeHistoryRequest
	11, // 19: challenge.ChallengeService.GetActiveOpenChallenges:input_type -> challenge.PaginationRequest
	14, // 20: challenge.ChallengeService.GetOwnersActiveChallenges:input_type -> challenge.GetOwnersActiveChallengesRequest
	15, // 21: challenge.ChallengeService.PushSubmissionStatus:input_type -> challenge.PushSubmissionStatusRequest
	8,  // 22: challenge.ChallengeService.CreateChallenge:output_type -> challenge.ChallengeRecord
	18, // 23: challenge.ChallengeService.AbandonChallenge:output_type -> challenge.AbandonChallengeResponse
	10, // 24: challenge.ChallengeService.GetChallengeRoomInfoMetadata:output_type -> challenge.GetChallengeRoomInfoMetadataResponse
	20, // 25: challenge.ChallengeService.GetFullChallengeData:output_type -> challenge.GetFullChallengeDataResponse
	12, // 26: challenge.ChallengeService.GetChallengeHistory:output_type -> challenge.ChallengeListResponse
	12, // 27: challenge.ChallengeService.GetActiveOpenChallenges:output_type -> challenge.ChallengeListResponse
	12, // 28: challenge.ChallengeService.GetOwnersActiveChallenges:output_type -> challenge.ChallengeListResponse
	16, // 29: challenge.ChallengeService.PushSubmissionStatus:output_type -> challenge.PushSubmissionStatusResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ChallengeService_challenge_proto_init() }
func file_ChallengeService_challenge_proto_init() {
	if File_ChallengeService_challenge_proto != nil {
		return
	}
	file_ChallengeService_challenge_proto_msgTypes[9].OneofWrappers = []any{}
	file_ChallengeService_challenge_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ChallengeService_challenge_proto_rawDesc), len(file_ChallengeService_challenge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ChallengeService_challenge_proto_goTypes,
		DependencyIndexes: file_ChallengeService_challenge_proto_depIdxs,
		MessageInfos:      file_ChallengeService_challenge_proto_msgTypes,
	}.Build()
	File_ChallengeService_challenge_proto = out.File
	file_ChallengeService_challenge_proto_goTypes = nil
	file_ChallengeService_challenge_proto_depIdxs = nil
}
